Data Cleaning and Preparation
-------------------------------
In this Notebook, I will clean the data and prepare it for Exploratory Data Analysis (EDA) and modeling. The dataset contains the collected GNIP data with the following columns:
- `Project Group Name`: Depicts how samples were collected (monthly, event, user submissions).
- `Latitude`: Latitude of the sample location.
- `Longitude`: Longitude of the sample location.
- `Altitude`: Altitude of the sample location.
- `Sample Date`: Date when the sample was collected.
- `Sample Date Accuracy`: Accuracy of the sample date.
- `Sample Media Type`: Type of media the sample was collected from (e.g., rain, snow, etc.).
- `Measurand Symbol`: Symbol representing the measurand
- `Measurand Amount`: Amount of the measurand.
- `Measurand Unit`: Unit of the measurand.
- `Observation Date`: Date when the observation was made.
- `Observation Date Accuracy`: Accuracy of the observation date.

In [2]:
# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# Load the dataset
dataDate_iter = '2025-07-05' # Date data was collected
data = pd.read_csv(f'GNIP_Uncleaned ({dataDate_iter}).csv', encoding='utf-8')

C:\Users\jaxgr\AppData\Local\Temp\ipykernel_6476\379827269.py:3: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(f'GNIP_Uncleaned ({dataDate_iter}).csv', encoding='utf-8')

## Remove Unnecessary Columns and Rename Columns
Columns kept:
- `Latitude` (Lat)
- `Longitude` (Lon)
- `Altitude` (Alt)
- `Observation Date` (Date)
- `Measurand Symbol` (Symbol)
- `Measurand Amount` (Amount)

In [ ]:
# Set the columns to keep
columns_to_keep = [
    'Latitude',
    'Longitude',
    'Altitude',
    'Observation Date',
    'Measurand Symbol',
    'Measurand Amount'
]
# Select only the necessary columns
df = data[columns_to_keep]

In [6]:
# Rename the columns for clarity
df = df.rename(columns={
    'Latitude': 'Lat',
    'Longitude': 'Lon',
    'Altitude': 'Alt',
    'Observation Date': 'Date',
    'Measurand Symbol': 'Symbol',
    'Measurand Amount': 'Amount'
})

In [7]:
df

,Lat,Lon,Alt,Date,Symbol,Amount
0,38.660389,-27.220094,74.0,1999-01-22T00:00:00.0000000+01:00,O18,-4.095
1,38.660389,-27.220094,74.0,1999-01-22T00:00:00.0000000+01:00,H2,-20.500
2,38.660389,-27.220094,74.0,1999-01-22T00:00:00.0000000+01:00,O18,-0.300
3,38.660389,-27.220094,74.0,1999-01-22T00:00:00.0000000+01:00,H2,1.500
4,38.660389,-27.220094,74.0,1999-01-22T00:00:00.0000000+01:00,O18,0.635
...,...,...,...,...,...,...
199776,36.555303,126.635925,62.0,NaN,H2,-64.950
199777,36.555303,126.635925,62.0,NaN,O18,-5.880
199778,36.555303,126.635925,62.0,NaN,H2,-44.210
199779,36.555303,126.635925,62.0,NaN,O18,-8.840
199780,36.555303,126.635925,62.0,NaN,H2,-45.270

## Convert Date Column to Datetime and set typing of other columns
Convert the columns to UTC timezone and set the typing of the other columns:
- `Lat`: float
- `Lon`: float
- `Alt`: float
- `Date`: datetime
- `Symbol`: string
- `Amount`: float

In [9]:
# Convert Date Column to Datetime
df['Date'] = pd.to_datetime(df['Date'], format='ISO8601', utc=True)

# Set the typing of the other columns
df['Lat'] = df['Lat'].astype(float)
df['Lon'] = df['Lon'].astype(float)
df['Alt'] = df['Alt'].astype(float)
df['Symbol'] = df['Symbol'].astype(str)
df['Amount'] = df['Amount'].astype(float)

In [10]:
df

              Lat         Lon   Alt                      Date Symbol  Amount
0       38.660389  -27.220094  74.0 1999-01-21 23:00:00+00:00    O18  -4.095
1       38.660389  -27.220094  74.0 1999-01-21 23:00:00+00:00     H2 -20.500
2       38.660389  -27.220094  74.0 1999-01-21 23:00:00+00:00    O18  -0.300
3       38.660389  -27.220094  74.0 1999-01-21 23:00:00+00:00     H2   1.500
4       38.660389  -27.220094  74.0 1999-01-21 23:00:00+00:00    O18   0.635
...           ...         ...   ...                       ...    ...     ...
199776  36.555303  126.635925  62.0                       NaT     H2 -64.950
199777  36.555303  126.635925  62.0                       NaT    O18  -5.880
199778  36.555303  126.635925  62.0                       NaT     H2 -44.210
199779  36.555303  126.635925  62.0                       NaT    O18  -8.840
199780  36.555303  126.635925  62.0                       NaT     H2 -45.270

[199781 rows x 6 columns]

## Pivot the DataFrame

In [11]:
df['O18'] = df[df['Symbol'] == 'O18']['Amount']
df['H2'] = df[df['Symbol'] == 'H2']['Amount']